# Generated by Django 4.0.3 on 2022-04-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userid',
            new_name='created_by',
        ),
    ]
