# Generated by Django 4.0.3 on 2022-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_listupload_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataformat', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
