# Generated by Django 4.0.3 on 2022-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_excelformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelformat',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
